### ISSUE TITLE
Error in usage example

### ISSUE THREAD

**Issue by sladex** [anasnakawa/grunt-css-prefix#4]
This may not work:

``` javascript
css_prefix: {
  files: {
    'dest/style.css': ['css/style.css']
  }
}
```

http://gruntjs.com/configuring-tasks#older-formats
And it didn't work for me (Grunt 0.4.1, nodejs 0.10.17). In the case above `files` treated as `task:target` name and `'dest/style.css': ['css/style.css']` just some unknown property name/value.
Correct examples:

``` javascript
css_prefix: {
  sometask: {
    files: {
      'dest/style.css': ['css/style.css']
    }
  }
}
```

``` javascript
css_prefix: {
  src: 'css/style.css',
  dest: 'dest/style.css'
}
```

``` javascript
css_prefix: {
  sometask: {
    src: 'css/style.css',
    dest: 'dest/style.css'
  }
}
```

**Comment by anasnakawa** [comment]
when you run this task, do you get any errors ?
there was a bug in versions prior to `0.2.1` that lead to some node submodules not being installed, make sure you get the latest `grunt-css-prefix`

btw grunt plugins has nothing to do with task structure, grunt should handle target files, and their options, not any plugin

**Comment by sladex** [comment]
No, no errors. I used the latest version.

```
>grunt css_prefix --verbose
.....
Running "css_prefix" task

Running "css_prefix:files" (css_prefix) task
Verifying property css_prefix.files exists in config...OK
File: [no files]

Done, without errors.
```

I have a feeling there is nothing wrong with `grunt-css-prefix`, the same behavior would be for all `grunt-init-gruntplugin` based plugins. Worth to check.

**Comment by anasnakawa** [comment]
you are correct,

I guess the example you gave won't work across all grunt plugins, as the task need to have a name.

will update my docs, thanks!
